version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dakoku-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ty3b269q0sud"
s3_prefix = "dakoku-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
