name: deploy-backEnd-application

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
      - "!**.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkoout
        uses: actions/checkout@v2

      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: sam setup
        uses: aws-actions/setup-sam@v2

      #AWS環境への認証
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: sam build
        run: sam build --use-container

      - name: sam deploy
        run: sam deploy
